services:
  lb-upload-server:
    image: ghcr.io/noflm/lb-upload-standalon:main
    container_name: lb-upload-standalone
    ports:
      - "30121:30121"
    volumes:
      # アップロードファイルを永続化
      - ./uploads:/app/uploads
      # ログを確認できるように（オプション）
      - ./logs:/app/logs
    environment:
      PORT: 30121
      UPLOAD_PATH: "./uploads"
      MAX_FILE_SIZE_MB: 50
      DEBUG: false
      CORS_MAX_AGE: 86400
      # DISCORD_WEBHOOK: "your_webhook_url_here"
      # API_KEY: "your_api_key_here"
      # CORS_ORIGIN: "http://localhost:3000,https://yourdomain.com"
    restart: unless-stopped
    # ヘルスチェック
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:30121/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s